name: gestion_pfe
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.0
  intl: ^0.17.0
  table_calendar: ^3.0.5  
  http: ^0.13.4
  image_picker: ^0.8.5+3
  icons_launcher: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
icons_launcher:
  image_path: 'assets/images/logo-epi.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true